In [2]:
import pandas as pd

In [3]:
phenotypes = pd.read_csv('/home/claudio/Comp_Genetics/raw_data/phenotypes_formatted.tsv', sep = '\t')
genotypes = pd.read_csv('/home/claudio/Comp_Genetics/raw_data/genotypes_noref_formatted.tsv', sep = '\t')

Extracting the sample names from the phenotypes and genotypes files

In [4]:
samples_genotypes = list(genotypes.columns.values[2:])
samples_genotypes.sort()

In [6]:
samples_phenotypes = list(phenotypes.drop_duplicates(subset=['ID']).iloc[:,1])

In [9]:
samples_phenotypes = [sample for sample in samples_phenotypes if sample != 'NT12001']

Are all the samples in the genotypes file present in the phenotype file? Which ones?

In [11]:
nomatch_samples = [sample for sample in samples_phenotypes if sample not in samples_genotypes]
nomatch_samples = list(dict.fromkeys(nomatch_samples))
print('Number of no-matching samples between files: {}, from a total of {}'.format(len(nomatch_samples), len(samples_genotypes)))
with open('/home/claudio/Comp_Genetics/result_true/nomatchingsamples.tsv', 'w') as fp:
    fp.write('\n'.join('{}'.format(sample) for sample in nomatch_samples))

Number of no-matching samples between files: 192, from a total of 694

What are the duplicate frequencies in the phenotype file?

In [12]:
import collections
import matplotlib.pyplot as plt

duplicate_frequencies = [(item,count) for item, count in collections.Counter(samples_phenotypes).items()]

with open('/home/claudio/Comp_Genetics/result_true/duplicate_samples.tsv', 'w') as fp:
    fp.write('\n'.join('{}\t{}'.format(element[0], element[1]) for element in duplicate_frequencies))

Formatting the table, clearing the no-matching samples in the phenotype file and saving

In [14]:
phenotypes_1 = phenotypes.drop_duplicates(subset=['ID'])
phenotypes_2 = phenotypes_1.drop(phenotypes.columns[0], axis = 1)
# ~ = negation
phenotypes_3 = phenotypes_2[~phenotypes_2['ID'].isin(nomatch_samples)]
phenotypes_3.to_csv('/home/claudio/Comp_Genetics/result_true/bugwas_phenotypes.tsv', sep = '\t', index =False)

Formatting the table and saving

In [ ]:
genotypes_1 = genotypes.rename(columns={"Unnamed: 0":"ps"})
genotypes_1.to_csv('/home/claudio/Comp_Genetics/result_true/bugwas_genotypes.tsv', sep = '\t', index = False)

In [19]:
genotypes_1

,NT12219,NT12588,NT12359,NT12611,NT12856,NT12603,NT12092,NT12111,NT12370,NT12136,...,NT12667,NT12539,NT12002,NT12010,NT12719,NT12184,NT12612,NT12452,NT12590,NT12400
0,T,T,T,T,T,T,T,C,T,T,...,T,C,T,T,T,T,T,T,T,T
1,G,G,G,G,G,G,G,G,G,G,...,G,G,G,G,G,G,G,G,G,G
2,T,C,T,T,T,T,T,T,T,T,...,T,T,T,T,T,T,T,T,T,T
3,T,T,T,T,T,T,T,T,T,T,...,T,T,T,T,T,T,T,T,T,T
4,G,G,G,G,G,G,G,G,G,G,...,G,G,G,G,G,G,G,G,G,G
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
590062,A,A,A,A,G,A,A,G,A,A,...,G,A,A,A,G,A,A,A,A,A
590063,C,C,C,C,C,C,C,C,C,C,...,C,C,C,C,C,C,C,C,C,C
590064,G,G,G,G,G,G,G,G,G,G,...,G,G,G,G,G,G,G,G,G,G
590065,A,A,A,A,A,A,A,A,A,A,...,A,A,A,A,A,A,A,A,A,A
590066,C,C,C,C,C,C,C,C,C,C,...,C,C,C,C,C,C,C,C,C,C